config/routes.rb
Rails.application.routes.draw do
  resources :users
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		get 'logout' => :destroy
		delete 'logout' => :destroy
	end
	
  resources :tickets
  resources :fixtures
  resources :teams
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fixture.rb
class Fixture < ApplicationRecord
	belongs_to :team
	has_many :tickets, dependent: :destroy
	validates :away_team, presence: true
	validates :stadium, presence: true
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  before_action :set_fixture, only: [:show, :edit, :update, :destroy]

  # GET /fixtures
  # GET /fixtures.json
  def index
    @fixtures = Fixture.all
  end

  # GET /fixtures/1
  # GET /fixtures/1.json
  def show
  end

  # GET /fixtures/new
  def new
    @fixture = Fixture.new
  end

  # GET /fixtures/1/edit
  def edit
  end

  # POST /fixtures
  # POST /fixtures.json
  def create
    @fixture = Fixture.new(fixture_params)

    respond_to do |format|
      if @fixture.save
        format.html { redirect_to @fixture, notice: 'Fixture was successfully created.' }
        format.json { render :show, status: :created, location: @fixture }
      else
        format.html { render :new }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixtures/1
  # PATCH/PUT /fixtures/1.json
  def update
    respond_to do |format|
      if @fixture.update(fixture_params)
        format.html { redirect_to @fixture, notice: 'Fixture was successfully updated.' }
        format.json { render :show, status: :ok, location: @fixture }
      else
        format.html { render :edit }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1
  # DELETE /fixtures/1.json
  def destroy
    @fixture.destroy
    respond_to do |format|
      format.html { redirect_to fixtures_url, notice: 'Fixture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fixture
      @fixture = Fixture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fixture_params
      params.require(:fixture).permit(:team_id, :away_team, :stadium, :time, :date)
    end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_form.html.erb
<%= form_with(model: fixture, local: true) do |form| %>
<body style="background-color:#3498DB;">
  <% if fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
      <% fixture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.collection_select :team_id, Team.all, :id, :team_Name %>
  </div>

  <div class="field">
    <%= form.label :away_team %>
    <%= form.text_field :away_team, id: :fixture_away_team %>
  </div>

  <div class="field">
    <%= form.label :stadium %>
    <%= form.text_field :stadium, id: :fixture_stadium %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :fixture_time %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :fixture_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</body>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Editing Fixture</h1>
<body style="background-color:#3498DB;">
<%= render 'form', fixture: @fixture %>

<%= link_to 'Show', @fixture %> |
<%= link_to 'Back', fixtures_path %>
</body>

app/views/fixtures/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= link_to 'Teams', teams_path %>
<%= link_to 'Tickets', tickets_path %>
<%= link_to 'Users', users_path %>
</h2>
<h1>Fixtures</h1>

<body style="background-color:#3498DB;">

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Away team</th>
      <th>Stadium</th>
      <th>Time</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fixtures.each do |fixture| %>
      <tr>
        <td><%= fixture.team.team_Name %></td>
        <td><%= fixture.away_team %></td>
        <td><%= fixture.stadium %></td>
        <td><%= fixture.time %></td>
        <td><%= fixture.date %></td>
        <td><%= link_to 'Show', fixture %></td>
        <td><%= link_to 'Edit', edit_fixture_path(fixture) %></td>
        <td><%= link_to 'Destroy', fixture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>

<%= link_to 'New Fixture', new_fixture_path %>

app/views/fixtures/new.html.erb
<h1>New Fixture</h1>
<body style="background-color:#3498DB;">
<%= render 'form', fixture: @fixture %>

<%= link_to 'Back', fixtures_path %>
</body>

app/views/fixtures/show.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color:#3498DB;">
<p>
  <strong>Team:</strong>
  <%= @fixture.team_id %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @fixture.away_team %>
</p>

<p>
  <strong>Stadium:</strong>
  <%= @fixture.stadium %>
</p>

<p>
  <strong>Time:</strong>
  <%= @fixture.time %>
</p>

<p>
  <strong>Date:</strong>
  <%= @fixture.date %>
</p>

<%= link_to 'Edit', edit_fixture_path(@fixture) %> |
<%= link_to 'Back', fixtures_path %>
</body>