config/routes.rb
Rails.application.routes.draw do
  resources :users
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		get 'logout' => :destroy
		delete 'logout' => :destroy
	end
	
  resources :tickets
  resources :fixtures
  resources :teams
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :fixture
	validates :fixture_id, presence: true
	validates :seat_type, presence: true
	validates :price, presence: true
	validates :no_of_tickets, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:fixture_id, :seat_type, :price, :no_of_tickets)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
<body style="background-color:#3498DB;">
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fixture_id %>
    <%= form.number_field :fixture_id, id: :ticket_fixture_id %>
  </div>

  <div class="field">
    <%= form.label :seat_type %>
    <%= form.text_field :seat_type, id: :ticket_seat_type %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :no_of_tickets %>
    <%= form.number_field :no_of_tickets, id: :ticket_no_of_tickets %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>
<body style="background-color:#3498DB;">
<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>
</body>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= link_to 'Teams', teams_path %>
<%= link_to 'Fixtures', fixtures_path %>
<%= link_to 'Users', users_path %>
</h2>
<h1>Tickets</h1>
<body style="background-color:#3498DB;">
<table>
  <thead>
    <tr>
      <th>Fixture</th>
      <th>Seat type</th>
      <th>Price</th>
      <th>No of tickets</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.fixture_id %></td>
        <td><%= ticket.seat_type %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.no_of_tickets %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>
<body style="background-color:#3498DB;">
<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>
</body>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color:#3498DB;">
<p>
  <strong>Fixture:</strong>
  <%= @ticket.fixture_id %>
</p>

<p>
  <strong>Seat type:</strong>
  <%= @ticket.seat_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>No of tickets:</strong>
  <%= @ticket.no_of_tickets %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>
</body>